title: Drupal cheatsheets
description: Drupal Cheatsheets
theme: minima
markdown: kramdown
lsi: false
safe: true
source: ./src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge