title: Drupal cheatsheets
description: Drupal Cheatsheets
theme: minima
markdown: kramdown
lsi: false
safe: true
source: ./src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-postcss
postcss:
  cache: false